name = "CatanLearning"
uuid = "4c91a4e0-7dfb-465a-9cbf-f9fc204cf8e7"
authors = ["Bryan Kaperick <bryankaperick@gmail.com>"]
version = "0.1.0"

[deps]
BetaML = "024491cd-cc6b-443e-8034-08ea7eb7db2b"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Catan = "f5a9156a-9005-488a-a606-ecf760a1f632"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
